inherit_gem:
  rubocop-config-crystal: .rubocop.yml

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false
